config/routes.rb
Rails.application.routes.draw do
  
  resources :genres
  resource :session
  
  get 'signup' => 'users#new'
  get "signin" => "sessions#new"
  
  resources :users
  root "movies#index"
  get 'movies/filter/:scope' => "movies#index", as: :filtered_movies

  resources :movies do
    resources :reviews
    resources :favorites
  end

end

app/views/layouts/_footer.html.erb
<div class="row">
<div class="large-12 columns">
<footer id="page-footer">

  <p>
    Copyright &copy; 2015
    <%= link_to 'The Pragmatic Studio','http://pragmaticstudio.com' %>
  </p>
</footer>
</div>
</div>

app/views/layouts/_header.html.erb
<div class="row">
<div class="large-12 columns">
<header id="page-header">
  <h1>Super-Heroic Flix</h1>
</header>

<nav>
  <p>
    <% if current_user %>
      <%= link_to current_user.name, current_user %>
      <%= link_to 'Sign Out', session_path, method: :delete, class: 'button' %>
    <% else %>
      <%= link_to 'Sign Up', signup_path, class: 'button' %>
      <%= link_to 'Sign In', new_session_path, class: 'button' %>
    <% end %>
  </p>
</nav>
</div>
</div>

app/views/layouts/_sidebar.html.erb
  <div class="rightside">
  <nav>
    <ul>
      <li class="movies">
        <%= link_to 'All Movies', movies_path, class: 'button' %>
      </li>

      <li class="movies">
        <%= link_to 'Hits', filtered_movies_path(:hits), class: 'button' %>
      </li>
      <li class="movies">
        <%= link_to 'Flops', filtered_movies_path(:flops), class: 'button' %>
      </li>
      <li class="movies">
        <%= link_to 'Upcoming', filtered_movies_path(:upcoming), class: 'button' %>
      </li>
      <li class="movies">
        <%= link_to 'Recent', filtered_movies_path(:recent), class: 'button' %>
      </li>


      <% if current_user_admin? %>
      <li>
        <%= link_to 'Add New Movie', new_movie_path %>
      </li>
      <% end %>
    </ul>
  </nav>
  <div class="side">
    <%= content_for(:side) %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
<%= render "layouts/header" %>

<div id="wrapper">
 <% if flash[:notice] %>
    <p class="flash notice">
      <%= flash[:notice] %>
    </p>
  <% end %>
  <% if flash[:alert] %>
  <p class="flash alert">
    <%= flash[:alert] %>
  </p>
<% end %>
 <div id="container">

  <body>

<div class="row">
  <div class="medium-12 columns">

    <div class="medium-9 columns">

      <%= yield %>
    </div>
    <div class="medium-3 columns">
  <%= render "layouts/sidebar" %>
  </div>
  </div>
</div>

<%= render "layouts/footer" %>
<br/>
  </body>
</html>